#!/bin/bash

echo ""
echo "🔧 OAuth Credential Configuration Fix"
echo "======================================"
echo ""

# Check current credentials
if grep -q "your-client-id.apps.googleusercontent.com" .env; then
    echo "❌ Problem: Using placeholder credentials in .env"
    echo ""
    echo "Current .env has:"
    echo "  GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
    echo "  GOOGLE_CLIENT_SECRET=your-client-secret"
    echo ""
    echo "These are NOT real credentials - that's why you're seeing 'invalid_client'"
    echo ""
else
    echo "✅ Real credentials detected in .env"
    echo ""
    # Show masked credentials
    CLIENT_ID=$(grep GOOGLE_CLIENT_ID .env | cut -d'=' -f2)
    CLIENT_SECRET=$(grep GOOGLE_CLIENT_SECRET .env | cut -d'=' -f2)
    echo "  Client ID: ${CLIENT_ID:0:30}..."
    echo "  Client Secret: ${CLIENT_SECRET:0:10}..."
    echo ""
    echo "⚠️  Credentials look configured but OAuth still failing."
    echo "   Common issues:"
    echo "   1. Client ID/Secret have extra spaces or newlines"
    echo "   2. Credentials are from wrong Google Cloud project"
    echo "   3. OAuth consent screen not configured"
    echo "   4. Redirect URI mismatch"
    echo ""
fi

echo "📋 How to Fix:"
echo ""
echo "Step 1: Get Real OAuth Credentials"
echo "───────────────────────────────────"
echo "1. Open: https://console.cloud.google.com/apis/credentials"
echo "2. Select your project (or create one)"
echo "3. Click 'Create Credentials' → 'OAuth client ID'"
echo ""
echo "   If prompted to configure consent screen:"
echo "   - User Type: Internal (for company-only access)"
echo "   - App name: Synthient"
echo "   - Support email: your email"
echo "   - Developer contact: your email"
echo "   - Save and Continue through all steps"
echo ""
echo "4. Application type: Web application"
echo "5. Name: Synthient OAuth"
echo "6. Authorized JavaScript origins:"
echo "   Add: http://localhost:3000"
echo ""
echo "7. Authorized redirect URIs:"
echo "   Add: http://localhost:3000/api/auth/google/callback"
echo "   ⚠️  Must match exactly! No trailing slash!"
echo ""
echo "8. Click Create"
echo "9. Copy the Client ID and Client Secret"
echo ""

echo "Step 2: Update .env File"
echo "────────────────────────"
echo "Edit .env and replace the placeholders:"
echo ""
echo "  nano .env"
echo ""
echo "Replace:"
echo "  GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "  GOOGLE_CLIENT_SECRET=your-client-secret"
echo ""
echo "With your actual credentials:"
echo "  GOOGLE_CLIENT_ID=123456789-abc123def456.apps.googleusercontent.com"
echo "  GOOGLE_CLIENT_SECRET=GOCSPX-YourActualSecretHere"
echo ""
echo "⚠️  Make sure there are NO:"
echo "   - Extra spaces before or after the values"
echo "   - Quote marks around the values"
echo "   - Newlines in the middle of values"
echo ""

echo "Step 3: Restart OAuth Server"
echo "─────────────────────────────"
echo "  pkill -f oauth-server.js"
echo "  node oauth-server.js > /tmp/oauth-server.log 2>&1 &"
echo ""
echo "Step 4: Test Again"
echo "──────────────────"
echo "  Open: http://localhost:3001"
echo "  Click: 'Continue with Google'"
echo ""

echo "═══════════════════════════════════════════"
echo ""
read -p "Press Enter to open Google Cloud Console..."
open "https://console.cloud.google.com/apis/credentials" 2>/dev/null || \
xdg-open "https://console.cloud.google.com/apis/credentials" 2>/dev/null || \
echo "Please manually open: https://console.cloud.google.com/apis/credentials"

echo ""
echo "After getting credentials, run:"
echo "  nano .env"
echo ""
